Павлов Вадим, 3й длинный контест, задача A
gigantpavlovv/hashmap_hse pull request #1
Opened 2019-03-05 18:20 UTC by gigantpavlovv

ссылка на сабмит(надеюсь): https://official.contest.yandex.ru/contest/11654/run-report/19413123/

2019-03-18 09:23 UTC, sartuhin requested changes
Вставьте побольше пустых строк для отделения методов, классов друг от друга. Также для логического разделения кусков кода внутри методов.

2019-03-18 09:23 UTC, sartuhin commented on hashmap.h
> +        //cout << "Y-1" << endl;
Нужно убрать дебаг вывод.

2019-03-18 09:23 UTC, sartuhin commented on hashmap.h
> +        size_t i = hasher(key) % table.size();
Название i хорошо подходит для однострочного фора.
В данном случае нужно придумать более говорящее название.

2019-03-18 09:23 UTC, sartuhin commented on hashmap.h
> +        }
В этом случае все будет работать и без _.

2019-03-18 21:24 UTC, gigantpavlovv commented
новая ссылка на сабмит: https://official.contest.yandex.ru/contest/11654/run-report/19681655/

2019-03-19 11:17 UTC, sartuhin requested changes

2019-03-19 11:17 UTC, sartuhin commented on hash_map.h
>              table.resize(2 * (cur_size + 1));
Избавьтесь от наименованных констант.

2019-03-27 10:18 UTC, gigantpavlovv commented
https://official.contest.yandex.ru/contest/11654/run-report/19781810/

2019-03-27 10:25 UTC, sartuhin approved these changes

2019-03-27 10:25 UTC, merged